apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2022-12-20T09:00:07Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: calculation-pipeline-5vvtnpvc
  namespace: tam-do
  resourceVersion: "70368871"
  selfLink: /api/v1/namespaces/tam-do/persistentvolumeclaims/calculation-pipeline-5vvtnpvc
  uid: 5d411d99-0585-4527-8ea5-9fca09e7f0bb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-5d411d99-0585-4527-8ea5-9fca09e7f0bb
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound